package com.consulo.flight.hibernate;
// Generated Jul 19, 2017 5:54:48 PM by Hibernate Tools 5.2.3.Final

/**
 * TestTable generated by hbm2java
 */
public class TestTable implements java.io.Serializable {

	private int id;
	private String name;

	public TestTable() {
	}

	public TestTable(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
